__title__ = "carbontracker"
__description__ = "Tracking and predicting the carbon footprint of training deep learning models."
__url__ = "https://github.com/lfwa/carbontracker"
__version__ = "1.1.6"
__author__ = "Lasse F. Wolff Anthony & Benjamin Kanding"
__license__ = "MIT"
