__title__ = "CarbonTracker"
__description__ = "Tracking and predicting carbon footprint of training deep learning models."
__url__ = "https://github.com/lfwa/carbontracker"
__version__ = "1.0.0"
__author__ = "Lasse F. Wolff Anthony & Benjamin Kanding"
__license__ = "MIT"